from __future__ import annotations

from typing import Protocol, TypeVar

RecordT = TypeVar("RecordT")


class ClaimableJobStore(Protocol[RecordT]):
    async def claim_next(self, worker_id: str, timeout_s: int = 1) -> RecordT | None: ...
    async def heartbeat(self, job_id: str, worker_id: str) -> bool: ...
    async def update(self, record: RecordT) -> None: ...
    async def close(self) -> None: ...
