from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    HTTP_ERROR = "HTTP_ERROR"
    BAD_REQUEST = "BAD_REQUEST"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"

    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    DOCUMENT_STORAGE_UNAVAILABLE = "DOCUMENT_STORAGE_UNAVAILABLE"
    DOCUMENT_UPLOAD_INVALID = "DOCUMENT_UPLOAD_INVALID"
    DOCUMENT_REPOSITORY_ERROR = "DOCUMENT_REPOSITORY_ERROR"
    DOCUMENT_BUCKET_MISSING = "DOCUMENT_BUCKET_MISSING"
    DOCUMENT_STORAGE_TIMEOUT = "DOCUMENT_STORAGE_TIMEOUT"
    DOCUMENT_STORAGE_AUTH_FAILED = "DOCUMENT_STORAGE_AUTH_FAILED"

    CLINICAL_CONFIG_NOT_FOUND = "CLINICAL_CONFIG_NOT_FOUND"
    CLINICAL_CONFIG_STORAGE_UNAVAILABLE = "CLINICAL_CONFIG_STORAGE_UNAVAILABLE"
    CLINICAL_CONFIG_INVALID = "CLINICAL_CONFIG_INVALID"
    CLINICAL_CONFIG_CONFLICT = "CLINICAL_CONFIG_CONFLICT"

    INFERENCE_REQUEST_FAILED = "INFERENCE_REQUEST_FAILED"
    INFERENCE_SERVICE_UNAVAILABLE = "INFERENCE_SERVICE_UNAVAILABLE"
    INFERENCE_TIMEOUT = "INFERENCE_TIMEOUT"
    INFERENCE_BAD_RESPONSE = "INFERENCE_BAD_RESPONSE"

    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    DEPENDENCY_TIMEOUT = "DEPENDENCY_TIMEOUT"
    DEPENDENCY_AUTH_FAILED = "DEPENDENCY_AUTH_FAILED"
    DEPENDENCY_BAD_RESPONSE = "DEPENDENCY_BAD_RESPONSE"

    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_VALIDATION_UNAVAILABLE = "AUTH_VALIDATION_UNAVAILABLE"
    AUTH_BAD_RESPONSE = "AUTH_BAD_RESPONSE"

    JOB_ALREADY_EXISTS = "JOB_ALREADY_EXISTS"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    RETRIEVAL_COLLECTION_NOT_READY = "RETRIEVAL_COLLECTION_NOT_READY"
