apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - redis.yaml
  - qdrant.yaml
  - minio.yaml
  - ollama.yaml
  - api.yaml
  - inference.yaml
  - worker.yaml
